import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import GameContextProvider from "./_shared/context/gameContext";
import ScoreContextProvider from "./_shared/context/scoreContext";

import "@/theme/globals.scss";

const outfit = Outfit({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ScoreContextProvider>
          <GameContextProvider>{children}</GameContextProvider>
        </ScoreContextProvider>
      </body>
    </html>
  );
}
